baseURL = 'http://nickmeier.xyz/'
languageCode = 'en-us'
title = "NickVTech"
theme = 'hugo-simplecss'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2

[[menu.main]]
name = "About Me"
url = "/about/"
weight = 3
